sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ignaciomendez99/react-docker -f Dockerfile.dev .

script:
  - docker run ignaciomendez99/react-docker yarn test -- --coverage
