sudo: required
services:
  - docker

before_install:
  - docker build -t ignaciomendez99/docker-react -f Dockerfile.dev  .

script:
  - docker run ignaciomendez99/docker-react npm run test -- --coverage
