version: '3'
services:
  react-app:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '4000:3000'
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    environment:
      - CHOKIDAR_USEPOLLING
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ['yarn', 'test']
